{
 "title": "Kubernetes apiservers",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count[1m])) by (instance)",
     "legendFormat": "{{ instance }} total"
    },
    {
     "expr": "sum(rate(apiserver_dropped_requests[1m])) by (instance)",
     "legendFormat": "{{ instance }} dropped"
    },
    {
     "expr": "sum(rate(apiserver_request_count{code=\"429\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} 429"
    },
    {
     "expr": "sum(rate(apiserver_request_count{code=\"404\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} 404"
    },
    {
     "expr": "sum(rate(apiserver_request_count{code=~\"4..\",code!=\"429\",code!=\"404\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} 4other"
    },
    {
     "expr": "sum(rate(apiserver_request_count{code=~\"5..\"}[1m])) by (instance)",
     "legendFormat": "{{ instance }} 5XX"
    }
   ]
  },
  {
   "title": "Short Request Latency (Secs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(apiserver_request_latencies_bucket{verb!~\"WATCH|CONNECT|LIST\"}[1m])) by (instance,resource,le))/1.0e6",
     "legendFormat": "median {{ instance }} {{ resource }}"
    }
   ]
  },
  {
   "title": "Current Number of Inflight Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apiserver_current_inflight_requests",
     "legendFormat": "{{ instance }} {{ requestKind }}"
    }
   ]
  },
  {
   "title": "Current Number of Long-Running Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apiserver_longrunning_gauge",
     "legendFormat": "{{ instance }} {{ resource }} {{ verb }} {{ scope }}"
    }
   ]
  },
  {
   "title": "longrunning, sum over instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_longrunning_gauge) without (instance)",
     "legendFormat": "{{ kubernetes_namespace }} {{ resource }} {{ verb }} {{ scope }}"
    }
   ]
  },
  {
   "title": "TokenReview Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{resource=\"tokenreviews\"}[1m])) by (instance, verb, code, client, contentType)",
     "legendFormat": "{{ instance }} {{ verb }} {{ code }} {{ client }} {{ contentType }}"
    }
   ]
  },
  {
   "title": "SubjectAccessReview Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{resource=\"subjectaccessreviews\"}[1m])) by (instance, verb, code, client, contentType)",
     "legendFormat": "{{ instance }} {{ verb }} {{ code }} {{ client }} {{ contentType }}"
    }
   ]
  },
  {
   "title": "Go Heap Bytes In Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{ instance }} {{ job }}" }
   ]
  },
  {
   "title": "Go GC CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum[1m])",
     "legendFormat": "{{instance}} {{job}}"
    }
   ]
  }
 ]
}