{
 "title": "KOS External",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Address Controller Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_ipam_attachment_create_to_address_latency_seconds_bucket[1m]))",
     "legendFormat": "99%ile address"
    },
    {
     "expr": "histogram_quantile(0.99, rate(kos_ipam_attachment_create_to_lock_latency_seconds_bucket[1m]))",
     "legendFormat": "99%ile lock"
    }
   ]
  },
  {
   "title": "99th Percentile Create-To-Interface Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_attachment_create_to_local_ifc_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "99th Percentile Create-to-Ready Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_attachment_create_to_status_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "99th Percentile of Ping Test Duration (secs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_attachment_exec_duration_secs_bucket[1m]))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Average Ping Test Duration (secs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_attachment_exec_duration_secs_sum[1m])/rate(kos_attachment_exec_duration_secs_count[1m])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Ping Tests/sec, by RC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_attachment_exec_rc[1m])",
     "legendFormat": "{{ node }} {{ RC }}"
    }
   ]
  },
  {
   "title": "99th Percentile Attachment Set-Address Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_ipam_attachment_update_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "99th Percentile Attachment Set-Ready Latency secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_attachment_status_latency_seconds_bucket[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}