{
 "title": "KOS Internals",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Requeue Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_queue_retries[1m])",
     "legendFormat": "ca @ {{ instance }}"
    },
    {
     "expr": "rate(kos_ipam_controller_queue_retries[1m])",
     "legendFormat": "ipam @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Enqueue Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(kos_agent_queue_adds[1m])", "legendFormat": "ca @ {{ instance }}" },
    {
     "expr": "rate(kos_ipam_controller_queue_adds[1m])",
     "legendFormat": "ipam @ {{ legend }}"
    }
   ]
  },
  {
   "title": "Dequeue Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_queue_queue_latency_count[1m])",
     "legendFormat": "ca @ {{ instance }}"
    },
    {
     "expr": "rate(kos_ipam_controller_queue_queue_latency_count[1m])",
     "legendFormat": "ipam @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kos_agent_queue_depth", "legendFormat": "ca @ {{ instance }}" },
    {
     "expr": "kos_ipam_controller_queue_depth",
     "legendFormat": "ipam @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Connection Agent Worker Utilization, summed over workers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_queue_work_duration_sum[1m])/1.0e6",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network Fabric utilization, summed over workers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kos_agent_fabric_latency_seconds_sum[1m])) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "99th Percentile Fabric Create*Port Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(kos_agent_fabric_latency_seconds_bucket{op=~\"Create.*Ifc\"}[1m]))",
     "legendFormat": "{{ op }}@{{ node }}"
    }
   ]
  },
  {
   "title": "90th Percentile Fabric Create*Port Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(kos_agent_fabric_latency_seconds_bucket{op=~\"Create.*Ifc\"}[1m]))",
     "legendFormat": "{{ op }}@{{ node }}"
    }
   ]
  },
  {
   "title": "Average CreateLocalPort Secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_fabric_latency_seconds_sum{op=\"CreateLocalIfc\"}[1m])/rate(kos_agent_fabric_latency_seconds_count{op=\"CreateLocalIfc\"}[1m])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Average CreateRemotePort secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_fabric_latency_seconds_sum{op=\"CreateRemoteIfc\"}[1m])/rate(kos_agent_fabric_latency_seconds_count{op=\"CreateRemoteIfc\"}[1m])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Average DeleteLocalPort Secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_fabric_latency_seconds_sum{op=\"DeleteLocalIfc\"}[1m])/rate(kos_agent_fabric_latency_seconds_count{op=\"DeleteLocalIfc\"}[1m])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Average DeleteRemotePort Secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_agent_fabric_latency_seconds_sum{op=\"DeleteRemoteIfc\"}[1m])/rate(kos_agent_fabric_latency_seconds_count{op=\"DeleteRemoteIfc\"}[1m])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Rate of Benefits from Special IPAM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kos_ipam_anticipation_used_sum[1m])",
     "legendFormat": "anticipation @ {{ instance }}"
    },
    {
     "expr": "rate(kos_ipam_status_used_sum[1m])",
     "legendFormat": "status @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Current Number of Local Attachments",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kos_agent_local_attachments", "legendFormat": "{{ node }}" }
   ]
  },
  {
   "title": "Current Number of Remote Attachments",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kos_agent_remote_attachments", "legendFormat": "{{ node }}" }
   ]
  }
 ]
}