// +build !ignore_autogenerated

/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	network "k8s.io/examples/staging/kos/pkg/apis/network"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_IPLock_To_network_IPLock,
		Convert_network_IPLock_To_v1alpha1_IPLock,
		Convert_v1alpha1_IPLockList_To_network_IPLockList,
		Convert_network_IPLockList_To_v1alpha1_IPLockList,
		Convert_v1alpha1_IPLockSpec_To_network_IPLockSpec,
		Convert_network_IPLockSpec_To_v1alpha1_IPLockSpec,
		Convert_v1alpha1_NetworkAttachment_To_network_NetworkAttachment,
		Convert_network_NetworkAttachment_To_v1alpha1_NetworkAttachment,
		Convert_v1alpha1_NetworkAttachmentErrors_To_network_NetworkAttachmentErrors,
		Convert_network_NetworkAttachmentErrors_To_v1alpha1_NetworkAttachmentErrors,
		Convert_v1alpha1_NetworkAttachmentList_To_network_NetworkAttachmentList,
		Convert_network_NetworkAttachmentList_To_v1alpha1_NetworkAttachmentList,
		Convert_v1alpha1_NetworkAttachmentSpec_To_network_NetworkAttachmentSpec,
		Convert_network_NetworkAttachmentSpec_To_v1alpha1_NetworkAttachmentSpec,
		Convert_v1alpha1_NetworkAttachmentStatus_To_network_NetworkAttachmentStatus,
		Convert_network_NetworkAttachmentStatus_To_v1alpha1_NetworkAttachmentStatus,
		Convert_v1alpha1_Subnet_To_network_Subnet,
		Convert_network_Subnet_To_v1alpha1_Subnet,
		Convert_v1alpha1_SubnetList_To_network_SubnetList,
		Convert_network_SubnetList_To_v1alpha1_SubnetList,
		Convert_v1alpha1_SubnetSpec_To_network_SubnetSpec,
		Convert_network_SubnetSpec_To_v1alpha1_SubnetSpec,
		Convert_v1alpha1_SubnetStatus_To_network_SubnetStatus,
		Convert_network_SubnetStatus_To_v1alpha1_SubnetStatus,
	)
}

func autoConvert_v1alpha1_IPLock_To_network_IPLock(in *IPLock, out *network.IPLock, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_IPLockSpec_To_network_IPLockSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_IPLock_To_network_IPLock is an autogenerated conversion function.
func Convert_v1alpha1_IPLock_To_network_IPLock(in *IPLock, out *network.IPLock, s conversion.Scope) error {
	return autoConvert_v1alpha1_IPLock_To_network_IPLock(in, out, s)
}

func autoConvert_network_IPLock_To_v1alpha1_IPLock(in *network.IPLock, out *IPLock, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_network_IPLockSpec_To_v1alpha1_IPLockSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_network_IPLock_To_v1alpha1_IPLock is an autogenerated conversion function.
func Convert_network_IPLock_To_v1alpha1_IPLock(in *network.IPLock, out *IPLock, s conversion.Scope) error {
	return autoConvert_network_IPLock_To_v1alpha1_IPLock(in, out, s)
}

func autoConvert_v1alpha1_IPLockList_To_network_IPLockList(in *IPLockList, out *network.IPLockList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]network.IPLock)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_IPLockList_To_network_IPLockList is an autogenerated conversion function.
func Convert_v1alpha1_IPLockList_To_network_IPLockList(in *IPLockList, out *network.IPLockList, s conversion.Scope) error {
	return autoConvert_v1alpha1_IPLockList_To_network_IPLockList(in, out, s)
}

func autoConvert_network_IPLockList_To_v1alpha1_IPLockList(in *network.IPLockList, out *IPLockList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]IPLock)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_network_IPLockList_To_v1alpha1_IPLockList is an autogenerated conversion function.
func Convert_network_IPLockList_To_v1alpha1_IPLockList(in *network.IPLockList, out *IPLockList, s conversion.Scope) error {
	return autoConvert_network_IPLockList_To_v1alpha1_IPLockList(in, out, s)
}

func autoConvert_v1alpha1_IPLockSpec_To_network_IPLockSpec(in *IPLockSpec, out *network.IPLockSpec, s conversion.Scope) error {
	out.SubnetName = in.SubnetName
	return nil
}

// Convert_v1alpha1_IPLockSpec_To_network_IPLockSpec is an autogenerated conversion function.
func Convert_v1alpha1_IPLockSpec_To_network_IPLockSpec(in *IPLockSpec, out *network.IPLockSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_IPLockSpec_To_network_IPLockSpec(in, out, s)
}

func autoConvert_network_IPLockSpec_To_v1alpha1_IPLockSpec(in *network.IPLockSpec, out *IPLockSpec, s conversion.Scope) error {
	out.SubnetName = in.SubnetName
	return nil
}

// Convert_network_IPLockSpec_To_v1alpha1_IPLockSpec is an autogenerated conversion function.
func Convert_network_IPLockSpec_To_v1alpha1_IPLockSpec(in *network.IPLockSpec, out *IPLockSpec, s conversion.Scope) error {
	return autoConvert_network_IPLockSpec_To_v1alpha1_IPLockSpec(in, out, s)
}

func autoConvert_v1alpha1_NetworkAttachment_To_network_NetworkAttachment(in *NetworkAttachment, out *network.NetworkAttachment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_NetworkAttachmentSpec_To_network_NetworkAttachmentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_NetworkAttachmentStatus_To_network_NetworkAttachmentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_NetworkAttachment_To_network_NetworkAttachment is an autogenerated conversion function.
func Convert_v1alpha1_NetworkAttachment_To_network_NetworkAttachment(in *NetworkAttachment, out *network.NetworkAttachment, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkAttachment_To_network_NetworkAttachment(in, out, s)
}

func autoConvert_network_NetworkAttachment_To_v1alpha1_NetworkAttachment(in *network.NetworkAttachment, out *NetworkAttachment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_network_NetworkAttachmentSpec_To_v1alpha1_NetworkAttachmentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_network_NetworkAttachmentStatus_To_v1alpha1_NetworkAttachmentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_network_NetworkAttachment_To_v1alpha1_NetworkAttachment is an autogenerated conversion function.
func Convert_network_NetworkAttachment_To_v1alpha1_NetworkAttachment(in *network.NetworkAttachment, out *NetworkAttachment, s conversion.Scope) error {
	return autoConvert_network_NetworkAttachment_To_v1alpha1_NetworkAttachment(in, out, s)
}

func autoConvert_v1alpha1_NetworkAttachmentErrors_To_network_NetworkAttachmentErrors(in *NetworkAttachmentErrors, out *network.NetworkAttachmentErrors, s conversion.Scope) error {
	out.IPAM = *(*[]string)(unsafe.Pointer(&in.IPAM))
	out.Host = *(*[]string)(unsafe.Pointer(&in.Host))
	return nil
}

// Convert_v1alpha1_NetworkAttachmentErrors_To_network_NetworkAttachmentErrors is an autogenerated conversion function.
func Convert_v1alpha1_NetworkAttachmentErrors_To_network_NetworkAttachmentErrors(in *NetworkAttachmentErrors, out *network.NetworkAttachmentErrors, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkAttachmentErrors_To_network_NetworkAttachmentErrors(in, out, s)
}

func autoConvert_network_NetworkAttachmentErrors_To_v1alpha1_NetworkAttachmentErrors(in *network.NetworkAttachmentErrors, out *NetworkAttachmentErrors, s conversion.Scope) error {
	out.IPAM = *(*[]string)(unsafe.Pointer(&in.IPAM))
	out.Host = *(*[]string)(unsafe.Pointer(&in.Host))
	return nil
}

// Convert_network_NetworkAttachmentErrors_To_v1alpha1_NetworkAttachmentErrors is an autogenerated conversion function.
func Convert_network_NetworkAttachmentErrors_To_v1alpha1_NetworkAttachmentErrors(in *network.NetworkAttachmentErrors, out *NetworkAttachmentErrors, s conversion.Scope) error {
	return autoConvert_network_NetworkAttachmentErrors_To_v1alpha1_NetworkAttachmentErrors(in, out, s)
}

func autoConvert_v1alpha1_NetworkAttachmentList_To_network_NetworkAttachmentList(in *NetworkAttachmentList, out *network.NetworkAttachmentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]network.NetworkAttachment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_NetworkAttachmentList_To_network_NetworkAttachmentList is an autogenerated conversion function.
func Convert_v1alpha1_NetworkAttachmentList_To_network_NetworkAttachmentList(in *NetworkAttachmentList, out *network.NetworkAttachmentList, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkAttachmentList_To_network_NetworkAttachmentList(in, out, s)
}

func autoConvert_network_NetworkAttachmentList_To_v1alpha1_NetworkAttachmentList(in *network.NetworkAttachmentList, out *NetworkAttachmentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]NetworkAttachment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_network_NetworkAttachmentList_To_v1alpha1_NetworkAttachmentList is an autogenerated conversion function.
func Convert_network_NetworkAttachmentList_To_v1alpha1_NetworkAttachmentList(in *network.NetworkAttachmentList, out *NetworkAttachmentList, s conversion.Scope) error {
	return autoConvert_network_NetworkAttachmentList_To_v1alpha1_NetworkAttachmentList(in, out, s)
}

func autoConvert_v1alpha1_NetworkAttachmentSpec_To_network_NetworkAttachmentSpec(in *NetworkAttachmentSpec, out *network.NetworkAttachmentSpec, s conversion.Scope) error {
	out.Node = in.Node
	out.Subnet = in.Subnet
	out.VNI = in.VNI
	return nil
}

// Convert_v1alpha1_NetworkAttachmentSpec_To_network_NetworkAttachmentSpec is an autogenerated conversion function.
func Convert_v1alpha1_NetworkAttachmentSpec_To_network_NetworkAttachmentSpec(in *NetworkAttachmentSpec, out *network.NetworkAttachmentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkAttachmentSpec_To_network_NetworkAttachmentSpec(in, out, s)
}

func autoConvert_network_NetworkAttachmentSpec_To_v1alpha1_NetworkAttachmentSpec(in *network.NetworkAttachmentSpec, out *NetworkAttachmentSpec, s conversion.Scope) error {
	out.Node = in.Node
	out.Subnet = in.Subnet
	out.VNI = in.VNI
	return nil
}

// Convert_network_NetworkAttachmentSpec_To_v1alpha1_NetworkAttachmentSpec is an autogenerated conversion function.
func Convert_network_NetworkAttachmentSpec_To_v1alpha1_NetworkAttachmentSpec(in *network.NetworkAttachmentSpec, out *NetworkAttachmentSpec, s conversion.Scope) error {
	return autoConvert_network_NetworkAttachmentSpec_To_v1alpha1_NetworkAttachmentSpec(in, out, s)
}

func autoConvert_v1alpha1_NetworkAttachmentStatus_To_network_NetworkAttachmentStatus(in *NetworkAttachmentStatus, out *network.NetworkAttachmentStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_NetworkAttachmentErrors_To_network_NetworkAttachmentErrors(&in.Errors, &out.Errors, s); err != nil {
		return err
	}
	out.LockUID = in.LockUID
	out.IPv4 = in.IPv4
	out.IfcName = in.IfcName
	out.HostIP = in.HostIP
	return nil
}

// Convert_v1alpha1_NetworkAttachmentStatus_To_network_NetworkAttachmentStatus is an autogenerated conversion function.
func Convert_v1alpha1_NetworkAttachmentStatus_To_network_NetworkAttachmentStatus(in *NetworkAttachmentStatus, out *network.NetworkAttachmentStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkAttachmentStatus_To_network_NetworkAttachmentStatus(in, out, s)
}

func autoConvert_network_NetworkAttachmentStatus_To_v1alpha1_NetworkAttachmentStatus(in *network.NetworkAttachmentStatus, out *NetworkAttachmentStatus, s conversion.Scope) error {
	if err := Convert_network_NetworkAttachmentErrors_To_v1alpha1_NetworkAttachmentErrors(&in.Errors, &out.Errors, s); err != nil {
		return err
	}
	out.LockUID = in.LockUID
	out.IPv4 = in.IPv4
	out.IfcName = in.IfcName
	out.HostIP = in.HostIP
	return nil
}

// Convert_network_NetworkAttachmentStatus_To_v1alpha1_NetworkAttachmentStatus is an autogenerated conversion function.
func Convert_network_NetworkAttachmentStatus_To_v1alpha1_NetworkAttachmentStatus(in *network.NetworkAttachmentStatus, out *NetworkAttachmentStatus, s conversion.Scope) error {
	return autoConvert_network_NetworkAttachmentStatus_To_v1alpha1_NetworkAttachmentStatus(in, out, s)
}

func autoConvert_v1alpha1_Subnet_To_network_Subnet(in *Subnet, out *network.Subnet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_SubnetSpec_To_network_SubnetSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_SubnetStatus_To_network_SubnetStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Subnet_To_network_Subnet is an autogenerated conversion function.
func Convert_v1alpha1_Subnet_To_network_Subnet(in *Subnet, out *network.Subnet, s conversion.Scope) error {
	return autoConvert_v1alpha1_Subnet_To_network_Subnet(in, out, s)
}

func autoConvert_network_Subnet_To_v1alpha1_Subnet(in *network.Subnet, out *Subnet, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_network_SubnetSpec_To_v1alpha1_SubnetSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_network_SubnetStatus_To_v1alpha1_SubnetStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_network_Subnet_To_v1alpha1_Subnet is an autogenerated conversion function.
func Convert_network_Subnet_To_v1alpha1_Subnet(in *network.Subnet, out *Subnet, s conversion.Scope) error {
	return autoConvert_network_Subnet_To_v1alpha1_Subnet(in, out, s)
}

func autoConvert_v1alpha1_SubnetList_To_network_SubnetList(in *SubnetList, out *network.SubnetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]network.Subnet)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_SubnetList_To_network_SubnetList is an autogenerated conversion function.
func Convert_v1alpha1_SubnetList_To_network_SubnetList(in *SubnetList, out *network.SubnetList, s conversion.Scope) error {
	return autoConvert_v1alpha1_SubnetList_To_network_SubnetList(in, out, s)
}

func autoConvert_network_SubnetList_To_v1alpha1_SubnetList(in *network.SubnetList, out *SubnetList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Subnet)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_network_SubnetList_To_v1alpha1_SubnetList is an autogenerated conversion function.
func Convert_network_SubnetList_To_v1alpha1_SubnetList(in *network.SubnetList, out *SubnetList, s conversion.Scope) error {
	return autoConvert_network_SubnetList_To_v1alpha1_SubnetList(in, out, s)
}

func autoConvert_v1alpha1_SubnetSpec_To_network_SubnetSpec(in *SubnetSpec, out *network.SubnetSpec, s conversion.Scope) error {
	out.IPv4 = in.IPv4
	out.VNI = in.VNI
	return nil
}

// Convert_v1alpha1_SubnetSpec_To_network_SubnetSpec is an autogenerated conversion function.
func Convert_v1alpha1_SubnetSpec_To_network_SubnetSpec(in *SubnetSpec, out *network.SubnetSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_SubnetSpec_To_network_SubnetSpec(in, out, s)
}

func autoConvert_network_SubnetSpec_To_v1alpha1_SubnetSpec(in *network.SubnetSpec, out *SubnetSpec, s conversion.Scope) error {
	out.IPv4 = in.IPv4
	out.VNI = in.VNI
	return nil
}

// Convert_network_SubnetSpec_To_v1alpha1_SubnetSpec is an autogenerated conversion function.
func Convert_network_SubnetSpec_To_v1alpha1_SubnetSpec(in *network.SubnetSpec, out *SubnetSpec, s conversion.Scope) error {
	return autoConvert_network_SubnetSpec_To_v1alpha1_SubnetSpec(in, out, s)
}

func autoConvert_v1alpha1_SubnetStatus_To_network_SubnetStatus(in *SubnetStatus, out *network.SubnetStatus, s conversion.Scope) error {
	out.Errors = *(*[]string)(unsafe.Pointer(&in.Errors))
	return nil
}

// Convert_v1alpha1_SubnetStatus_To_network_SubnetStatus is an autogenerated conversion function.
func Convert_v1alpha1_SubnetStatus_To_network_SubnetStatus(in *SubnetStatus, out *network.SubnetStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_SubnetStatus_To_network_SubnetStatus(in, out, s)
}

func autoConvert_network_SubnetStatus_To_v1alpha1_SubnetStatus(in *network.SubnetStatus, out *SubnetStatus, s conversion.Scope) error {
	out.Errors = *(*[]string)(unsafe.Pointer(&in.Errors))
	return nil
}

// Convert_network_SubnetStatus_To_v1alpha1_SubnetStatus is an autogenerated conversion function.
func Convert_network_SubnetStatus_To_v1alpha1_SubnetStatus(in *network.SubnetStatus, out *SubnetStatus, s conversion.Scope) error {
	return autoConvert_network_SubnetStatus_To_v1alpha1_SubnetStatus(in, out, s)
}
